version: '3'
services:
  www:
    image: ghcr.io/dawenhaozx/sn
    volumes:
      - './v2board:/www'
      - './wwwlogs:/wwwlogs'
      - './caddy.conf:/run/caddy/caddy.conf'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './.caddy:/root/.caddy'
    links:
      - mysql
    ports:
      - '80:80'
      - '7001:7001'
      - '6600:6600'
      - '443:443'
#      - '443:443'
    restart: always
  mysql:
    image: arm64v8/mysql:latest
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'DataBase_password'
      MYSQL_DATABASE: 'DB_Name'
